export const REQUEST_USER_REGISTER = 'REQUEST_USER_REGISTER';
export const SUCCESS_USER_REGISTER = 'SUCCESS_USER_REGISTER';
export const FAIL_USER_REGISTER = 'FAIL_USER_REGISTER';

export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const SUCCESS_USER_LOGIN = 'SUCCESS_USER_LOGIN';
export const FAIL_USER_LOGIN = 'FAIL_USER_LOGIN';
